version: '3'

services:
  mongodb:
    image: mongo:6.0.13-rc0-jammy
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: learning_nest_pokemon
    volumes:
      - ./mongo:/data/db
